# LOCAL ENV TESTS
###
GET http://localhost:3000/

###
GET http://localhost:3000/contacts

###
GET http://localhost:3000/contacts/6814f5a340cdf656cd55d0e1

###
POST http://localhost:3000/contacts
Content-Type: application/json

{
    "firstName": "Thierry",
    "lastName": "Henry",
    "email": "henry27@gmail.com",
    "favoriteColor": "Yellow",
    "birthday": "1980-09-23"
}

###
PUT http://localhost:3000/contacts/6814f5a340cdf656cd55d0e1
Content-Type: application/json

{
    "firstName": "Cristiano Updated",
    "lastName": "Ronaldo",
    "email": "cristianoronaldo@gmail.com",
    "favoriteColor": "blue",
    "birthday": "1988-05-19"

}

# PROD ENV TESTS
###
GET https://nefi341-test-name.onrender.com/

###
GET https://nefi341-test-name.onrender.com/contacts/

###
GET https://nefi341-test-name.onrender.com/contacts/6814f5a340cdf656cd55d0e1