# LOCAL ENV TESTS
###
GET http://localhost:3000/

###
GET http://localhost:3000/contacts

###
GET http://localhost:3000/contacts/6814f5a340cdf656cd55d0e1

###
POST http://localhost:3000/contacts
Content-Type: application/json

{
    "name": "TEst",
    "firstName": "TEst",
    "lastName": "TEst",
    "email": "TEst",
    "favoriteColor": "TEst",
    "birthday": "1999-01-01"
}

# PROD ENV TESTS
###
GET https://nefi341-test-name.onrender.com/

###
GET https://nefi341-test-name.onrender.com/contacts/

###
GET https://nefi341-test-name.onrender.com/contacts/6814f5a340cdf656cd55d0e1